
name: Stage_Test

on:
  repository_dispatch:
    types: [stage-sync-success]

jobs:
  Test_Stage:
    name: "Test Stage"
    runs-on: ubuntu-latest
    environment: az-vote-app-stage
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.event.client_payload.sha }}
    - name: Automated test
      run: |
        chmod +x ${{ github.workspace }}/utils/smoke-test.sh
        ${{ github.workspace }}/utils/smoke-test.sh ${{ secrets.CLUSTER_ENTRY_URL }}${{ secrets.DEMO_APP_URL }}
  
